spring.application.name=CapstoneProject
spring.config.import=env.properties

# SERVER CONFIG
server.port=${PORTA}
#DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
#JWT
jwt.secret=${JWT_SECRET}
#CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.name=${ADMIN_NAME}
admin.surname=${ADMIN_SURNAME}
admin.phone=${ADMIN_PHONE}